const js = require('@eslint/js');
const prettier = require('eslint-config-prettier');

module.exports = [
    js.configs.recommended,
    prettier,
    {
        languageOptions: {
            ecmaVersion: 2022,
            sourceType: 'commonjs',
            globals: {
                require: 'readonly',
                module: 'readonly',
                exports: 'readonly',
                process: 'readonly',
                __dirname: 'readonly',
                __filename: 'readonly',
                console: 'readonly',
                setTimeout: 'readonly',
                setInterval: 'readonly',
                clearTimeout: 'readonly',
                clearInterval: 'readonly',
                Buffer: 'readonly',
                URL: 'readonly',
                URLSearchParams: 'readonly',
                fetch: 'readonly',
                AbortController: 'readonly',
                Promise: 'readonly',
                Map: 'readonly',
                Set: 'readonly',
                Date: 'readonly',
                Math: 'readonly',
                JSON: 'readonly',
                parseInt: 'readonly',
                parseFloat: 'readonly',
                Number: 'readonly',
                Array: 'readonly',
                Object: 'readonly',
                String: 'readonly',
                Error: 'readonly',
                RegExp: 'readonly',
                Symbol: 'readonly',
                TypeError: 'readonly',
                RangeError: 'readonly',
                describe: 'readonly',
                it: 'readonly',
                expect: 'readonly',
                beforeEach: 'readonly',
                vi: 'readonly',
            },
        },
        rules: {
            'no-unused-vars': ['warn', { argsIgnorePattern: '^_', varsIgnorePattern: '^_' }],
            'no-console': 'off',
            'no-constant-condition': 'warn',
            'no-empty': ['warn', { allowEmptyCatch: true }],
            'no-prototype-builtins': 'warn',
            'no-undef': 'error',
            'no-redeclare': 'error',
            'eqeqeq': ['warn', 'always'],
            'no-var': 'warn',
            'prefer-const': 'warn',
        },
    },
    {
        ignores: ['node_modules/**', 'public/**', 'views/**', 'docs/**', 'coverage/**'],
    },
];
