'use strict';

/**
 * Sitemap Export Service
 *
 * Renders sitemap output in multiple formats and serves a static XSL stylesheet:
 *
 *   - renderXml          — wraps a generated urlset/index with <?xml-stylesheet?>
 *   - renderHtmlSitemap  — visual site map grouped by section
 *   - renderCsv          — flat CSV of URLs + lastmod + priority + counts
 *   - renderTxt          — one URL per line
 *   - renderGzipped      — gzip the XML (Node built-in zlib)
 *   - renderXslStylesheet — static XSLT that styles XML for browser view
 *   - renderRobotsTxt    — robots.txt with optional Sitemap: directive
 *
 * All output is UTF-8. The XSL template is cached at module level.
 */

const zlib = require('zlib');
const { escapeXml, getPathSegment } = require('./sitemapGeneratorService');

const XSL_STYLESHEET = `<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
  <xsl:output method="html" version="1.0" encoding="UTF-8" indent="yes"/>
  <xsl:template match="/">
    <html lang="en">
      <head>
        <meta charset="UTF-8"/>
        <title>Sitemap — <xsl:value-of select="/urlset/url[1]/loc"/></title>
        <style>
          body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif; background: #f7f8fa; color: #1f2937; margin: 0; padding: 24px; }
          h1   { color: #1e40af; margin: 0 0 8px; }
          .sub { color: #6b7280; font-size: 14px; margin-bottom: 24px; }
          table { width: 100%; border-collapse: collapse; background: #fff; box-shadow: 0 1px 3px rgba(0,0,0,.08); border-radius: 8px; overflow: hidden; }
          th, td { text-align: left; padding: 10px 14px; border-bottom: 1px solid #e5e7eb; font-size: 14px; }
          th { background: #1e40af; color: #fff; font-weight: 600; }
          tr:hover td { background: #f9fafb; }
          a { color: #1e40af; text-decoration: none; word-break: break-all; }
          a:hover { text-decoration: underline; }
          .count { background: #ecfdf5; color: #047857; padding: 2px 10px; border-radius: 12px; font-size: 13px; font-weight: 600; }
        </style>
      </head>
      <body>
        <h1>XML Sitemap</h1>
        <p class="sub">
          <span class="count"><xsl:value-of select="count(/urlset/url)"/> URLs</span>
          · Generated by Keyword Analyzer · Google-spec compliant
        </p>
        <table>
          <thead>
            <tr><th>#</th><th>URL</th><th>Last modified</th><th>Change freq.</th><th>Priority</th></tr>
          </thead>
          <tbody>
            <xsl:for-each select="/urlset/url">
              <tr>
                <td><xsl:value-of select="position()"/></td>
                <td><a href="{loc}"><xsl:value-of select="loc"/></a></td>
                <td><xsl:value-of select="lastmod"/></td>
                <td><xsl:value-of select="changefreq"/></td>
                <td><xsl:value-of select="priority"/></td>
              </tr>
            </xsl:for-each>
          </tbody>
        </table>
      </body>
    </html>
  </xsl:template>
</xsl:stylesheet>`;

let _cachedXsl = null;

function renderXslStylesheet() {
    if (_cachedXsl) return _cachedXsl;
    _cachedXsl = XSL_STYLESHEET;
    return _cachedXsl;
}

/**
 * Wrap a urlset / sitemapindex with an XSL stylesheet reference.
 * The stylesheet lets browsers view the XML as a styled HTML page.
 */
function renderXml(xml) {
    if (!xml || typeof xml !== 'string') return xml;
    if (xml.startsWith('<?xml-stylesheet')) return xml;
    // Insert <?xml-stylesheet ...?> after the XML declaration
    const stylesheetLine = '<?xml-stylesheet type="text/xsl" href="/sitemap.xsl" media="screen"?>';
    return xml.replace(/^(<\?xml[^?]+\?>)/, `$1\n${stylesheetLine}`);
}

function csvEscape(value) {
    if (value === null || value === undefined) return '';
    const s = String(value);
    if (/[",\n]/.test(s)) return `"${s.replace(/"/g, '""')}"`;
    return s;
}

function renderCsv(pages) {
    const header = 'loc,lastmod,changefreq,priority,image_count,video_count,news_flag';
    const rows = pages.map(p => [
        csvEscape(p.url),
        csvEscape(p.lastmod || ''),
        csvEscape(p.changefreq || ''),
        csvEscape(p.priority || ''),
        (p.images || []).length,
        (p.videos || []).length,
        (p.news   || []).length > 0 ? 'yes' : 'no',
    ].join(','));
    return [header, ...rows].join('\n');
}

function renderTxt(pages) {
    return pages.map(p => p.url).join('\n') + (pages.length > 0 ? '\n' : '');
}

function renderGzipped(xml) {
    return zlib.gzipSync(Buffer.from(xml, 'utf8'), { level: 9 });
}

function htmlEscape(s) {
    return String(s)
        .replace(/&/g, '&amp;')
        .replace(/</g, '&lt;')
        .replace(/>/g, '&gt;')
        .replace(/"/g, '&quot;')
        .replace(/'/g, '&#39;');
}

function renderHtmlSitemap(pages, opts = {}) {
    const title = opts.title || 'HTML Sitemap';
    const description = opts.description || 'A visual, human-readable view of this site.';
    const grouped = new Map();
    for (const p of pages) {
        const section = getPathSegment(p.url);
        if (!grouped.has(section)) grouped.set(section, []);
        grouped.get(section).push(p);
    }
    const totalUrls = pages.length;
    const generated = new Date().toISOString();

    const sectionBlocks = [];
    for (const [section, items] of [...grouped.entries()].sort((a, b) => a[0].localeCompare(b[0]))) {
        sectionBlocks.push(`
            <details class="sitemap-section" open>
                <summary><strong>${htmlEscape(section)}</strong> <span class="count">${items.length} URL${items.length !== 1 ? 's' : ''}</span></summary>
                <ul class="sitemap-list">
                    ${items.map(p => `<li><a href="${htmlEscape(p.url)}">${htmlEscape(p.url)}</a> <span class="meta">${htmlEscape(p.lastmod || '')} · ${htmlEscape(p.changefreq || '')} · ${htmlEscape(p.priority || '')}</span></li>`).join('')}
                </ul>
            </details>`);
    }

    return `<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8"/>
    <meta name="viewport" content="width=device-width,initial-scale=1"/>
    <title>${htmlEscape(title)}</title>
    <style>
        :root { --c-bg: #f7f8fa; --c-card: #fff; --c-text: #1f2937; --c-muted: #6b7280; --c-primary: #1e40af; --c-border: #e5e7eb; }
        body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif; background: var(--c-bg); color: var(--c-text); margin: 0; padding: 32px; max-width: 1100px; margin: 0 auto; }
        h1   { color: var(--c-primary); margin: 0 0 6px; }
        .sub { color: var(--c-muted); font-size: 14px; margin-bottom: 24px; }
        .count { background: #ecfdf5; color: #047857; padding: 2px 10px; border-radius: 12px; font-size: 12px; font-weight: 600; }
        .sitemap-section { background: var(--c-card); border: 1px solid var(--c-border); border-radius: 8px; margin-bottom: 12px; padding: 12px 18px; }
        .sitemap-section summary { cursor: pointer; font-size: 16px; }
        .sitemap-list { margin: 12px 0 0; padding-left: 20px; }
        .sitemap-list li { padding: 4px 0; font-size: 14px; }
        .sitemap-list a { color: var(--c-primary); text-decoration: none; word-break: break-all; }
        .sitemap-list a:hover { text-decoration: underline; }
        .meta { color: var(--c-muted); font-size: 12px; margin-left: 8px; }
        footer { color: var(--c-muted); font-size: 12px; text-align: center; margin-top: 32px; }
    </style>
</head>
<body>
    <h1>${htmlEscape(title)}</h1>
    <p class="sub">${htmlEscape(description)} · <span class="count">${totalUrls} URL${totalUrls !== 1 ? 's' : ''}</span></p>
    ${sectionBlocks.join('\n')}
    <footer>Generated ${generated} · Google-spec compliant XML sitemap</footer>
</body>
</html>`;
}

function renderRobotsTxt({ sitemapUrl, userAgent = '*', allow = ['/'], disallow = [] } = {}) {
    const lines = [];
    if (userAgent) lines.push(`User-agent: ${userAgent}`);
    for (const a of (allow || [])) lines.push(`Allow: ${a}`);
    for (const d of (disallow || [])) lines.push(`Disallow: ${d}`);
    if (sitemapUrl) lines.push(`Sitemap: ${sitemapUrl}`);
    return lines.join('\n') + '\n';
}

module.exports = {
    renderXml,
    renderXslStylesheet,
    renderHtmlSitemap,
    renderCsv,
    renderTxt,
    renderGzipped,
    renderRobotsTxt,
};
